<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hunan</name>
   <tag></tag>
   <elementGuidId>f93adf29-4a63-452b-86e0-39f85fe68179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.el-tree-node__expand-icon.el-icon-caret-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@element-loading-text='拼命加载中']/div[1]/div[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-tree-node__expand-icon el-icon-caret-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-6680&quot;)/div[@class=&quot;tree&quot;]/div[@class=&quot;el-tree el-tree--highlight-current&quot;]/div[@class=&quot;el-tree-node is-current is-focusable&quot;]/div[@class=&quot;el-tree-node__content&quot;]/span[@class=&quot;el-tree-node__expand-icon el-icon-caret-right&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-menu-6680']/div/div/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
